"""add partner ownership

Revision ID: 52a57e95531a
Revises: f58943f5a6d5
Create Date: 2022-07-29 03:20:36.594529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a57e95531a'
down_revision = 'f58943f5a6d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_partners_users', 'partners', 'users', ['owner_id'], ['id'])
    op.create_unique_constraint('uq_user_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'users', type_='unique')
    op.drop_constraint('fk_partners_users', 'partners', type_='foreignkey')
    op.drop_column('partners', 'owner_id')
    # ### end Alembic commands ###
