"""add reset code on user

Revision ID: 8dcbdeb4c696
Revises: af7f0d4890ee
Create Date: 2022-07-27 16:05:46.482184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcbdeb4c696'
down_revision = 'af7f0d4890ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
