"""add auth model

Revision ID: b2eff0dee2c0
Revises: 3b6623c79786
Create Date: 2022-07-26 16:32:07.428423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2eff0dee2c0'
down_revision = '3b6623c79786'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token', 'user_id', 'token_type', 'is_active')
    )
    op.create_index('idx_auth_token_access_token_created_at', 'auth_token', ['access_token', sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_auth_token_access_token'), 'auth_token', ['access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_token_access_token'), table_name='auth_token')
    op.drop_index('idx_auth_token_access_token_created_at', table_name='auth_token')
    op.drop_table('auth_token')
    # ### end Alembic commands ###
